# Generated by Django 5.1 on 2024-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateofadmission',
            field=models.DateField(blank=True, db_column='DateOfAdmission', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, db_column='DOB', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(blank=True, db_column='FirstName', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, db_column='Gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(blank=True, db_column='LastName', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.CharField(blank=True, db_column='PhoneNo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(db_column='Rollno', primary_key=True, serialize=False),
        ),
    ]
